SELECT_APEX_USERS = 'SELECT * FROM `apex_users` ORDER BY `id`;'
SELECT_APEX_USER_BY_UID = 'SELECT * FROM `apex_users` WHERE `uid` = %(uid)s;'
# UPDATE_APEX_USER_BY_UID = 'UPDATE `apex_users` SET `name`=%(name)s WHERE `uid` = %(uid)s;'
UPDATE_APEX_USER_BY_UID = 'INSERT INTO `apex_users` (`level`, `name`, `uid`, `platform`) VALUES (%(level)s, %(name)s, %(uid)s, %(platform)s) ON DUPLICATE KEY UPDATE `level` = %(level)s;'
UPDATE_APEX_USER_BY_NAME = 'INSERT INTO `apex_users` (`level`, `name`, `uid`, `platform`) VALUES (%(level)s, %(name)s, %(uid)s, %(platform)s) ON DUPLICATE KEY UPDATE `level` = %(level)s'
DELETE_APEX_USER_BY_UID = 'DELETE FROM `apex_users` WHERE `uid` = %(uid)s;'
DELETE_APEX_USER_BY_NAME = 'DELETE FROM `apex_users` WHERE `name` = %(name)s;'

SELECT_APEX_USER_RANKS = 'SELECT * FROM `apex_user_ranks` ORDER BY `id`;'
SELECT_APEX_USER_RANK_BY_UID = 'SELECT * FROM `apex_user_ranks` WHERE `apex_user_id` = (SELECT `id` FROM `apex_users` WHERE `uid` = %(uid)s) ORDER BY `id`;'
SELECT_APEX_USER_RANK_BY_NAME = 'SELECT * FROM `apex_user_ranks` WHERE `apex_user_id` = (SELECT `id` FROM `apex_users` WHERE `name` = %(name)s) ORDER BY `id`;'
# UPDATE_APEX_USER_RANK = ''
INSERT_APEX_USER_RANK_BY_UID = 'INSERT INTO `apex_user_ranks`(`apex_user_id`, `season`, `split`, `battle_score`, `battle_name`, `battle_division`, `arena_score`, `arena_name`, `arena_division`) VALUES (SELECT `id` FROM `apex_users` WHERE `uid` = %(uid)s, %(season)s, %(split)s, %(battle_score)s, %(battle_name)s, %(battle_division)s, %(arena_score)s, %(arena_name)s, %(arena_division)s);'
INSERT_APEX_USER_RANK_BY_NAME = 'INSERT INTO `apex_user_ranks`(`apex_user_id`, `season`, `split`, `battle_score`, `battle_name`, `battle_division`, `arena_score`, `arena_name`, `arena_division`) VALUES (SELECT `id` FROM `apex_users` WHERE `name` = %(name)s, %(season)s, %(split)s, %(battle_score)s, %(battle_name)s, %(battle_division)s, %(arena_score)s, %(arena_name)s, %(arena_division)s);'
# DELETE_APEX_USER_RANK = ''